# Generated by Django 3.2.15 on 2022-10-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='playlist_pics'),
        ),
    ]
