# Generated by Django 3.2.15 on 2022-11-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='placeholder-image.jpg', upload_to='playlist_pics/'),
        ),
    ]
