# Generated by Django 3.2.15 on 2022-10-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20221022_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='creator',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='placeholder-image.jpg', upload_to='playlist_pics'),
        ),
    ]
