# Generated by Django 3.2.15 on 2022-10-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20221022_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user',
            new_name='creator',
        ),
    ]
